version: "3.7"

services:
    platby:
        image: "veldik/platby:latest"
        build:
            context: .
            args:
                BASE_TAG: latest
                network: default
        container_name: "platby"
        restart: "always"
        volumes:
            - ./:/var/www/html
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.platby-sec.entrypoints=websecure"
            - "traefik.http.routers.platby-sec.rule=Host(`api.platby.thevelda.eu`)"
            - "traefik.http.routers.platby-sec.tls.certresolver=lets-encrypt"
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 256M

networks:
    default:
        external:
            name: webhosting
