version: "3.7"

services:
    platby:
        image: "veldik/educa-sis:latest"
        build:
            context: .
            args:
                BASE_TAG: latest
                network: default
        container_name: "platby"
        restart: "always"
        volumes:
            - ./:/var/www/html
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nextcloud-sec.entrypoints=websecure"
            - "traefik.http.routers.nextcloud-sec.rule=Host(`platby.thevelda.eu`)"
            - "traefik.http.routers.nextcloud-sec.tls.certresolver=lets-encrypt"

networks:
    default:
        external:
            name: webhosting
